require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeavesController do

  # This should return the minimal set of attributes required to create a valid
  # Leave. As you add validations to Leave, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeavesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leaves as @leaves" do
      leave = Leave.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leaves).should eq([leave])
    end
  end

  describe "GET show" do
    it "assigns the requested leave as @leave" do
      leave = Leave.create! valid_attributes
      get :show, {:id => leave.to_param}, valid_session
      assigns(:leave).should eq(leave)
    end
  end

  describe "GET new" do
    it "assigns a new leave as @leave" do
      get :new, {}, valid_session
      assigns(:leave).should be_a_new(Leave)
    end
  end

  describe "GET edit" do
    it "assigns the requested leave as @leave" do
      leave = Leave.create! valid_attributes
      get :edit, {:id => leave.to_param}, valid_session
      assigns(:leave).should eq(leave)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Leave" do
        expect {
          post :create, {:leave => valid_attributes}, valid_session
        }.to change(Leave, :count).by(1)
      end

      it "assigns a newly created leave as @leave" do
        post :create, {:leave => valid_attributes}, valid_session
        assigns(:leave).should be_a(Leave)
        assigns(:leave).should be_persisted
      end

      it "redirects to the created leave" do
        post :create, {:leave => valid_attributes}, valid_session
        response.should redirect_to(Leave.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leave as @leave" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leave.any_instance.stub(:save).and_return(false)
        post :create, {:leave => {}}, valid_session
        assigns(:leave).should be_a_new(Leave)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leave.any_instance.stub(:save).and_return(false)
        post :create, {:leave => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leave" do
        leave = Leave.create! valid_attributes
        # Assuming there are no other leaves in the database, this
        # specifies that the Leave created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Leave.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => leave.to_param, :leave => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested leave as @leave" do
        leave = Leave.create! valid_attributes
        put :update, {:id => leave.to_param, :leave => valid_attributes}, valid_session
        assigns(:leave).should eq(leave)
      end

      it "redirects to the leave" do
        leave = Leave.create! valid_attributes
        put :update, {:id => leave.to_param, :leave => valid_attributes}, valid_session
        response.should redirect_to(leave)
      end
    end

    describe "with invalid params" do
      it "assigns the leave as @leave" do
        leave = Leave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leave.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave.to_param, :leave => {}}, valid_session
        assigns(:leave).should eq(leave)
      end

      it "re-renders the 'edit' template" do
        leave = Leave.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Leave.any_instance.stub(:save).and_return(false)
        put :update, {:id => leave.to_param, :leave => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leave" do
      leave = Leave.create! valid_attributes
      expect {
        delete :destroy, {:id => leave.to_param}, valid_session
      }.to change(Leave, :count).by(-1)
    end

    it "redirects to the leaves list" do
      leave = Leave.create! valid_attributes
      delete :destroy, {:id => leave.to_param}, valid_session
      response.should redirect_to(leaves_url)
    end
  end

end
